### ISSUE TITLE
Change the default colouring scheme for blocks of code

### ISSUE THREAD

**Issue by b1azk0** [nodejh/hugo-theme-cactus-plus#42]
Is there an easy way to change the default coloring scheme of block of code?

Looks the theme defaults to `highlight: zenburn` from RMakrdown documents but I'm not 100%sure.
In a regular RMarkdownw document I would change html output in yaml to:
```
output:
  html_document:
    theme: united
    highlight: tango
```

But with hugo themes and blogdown I'm not sure where and how make these changes.

(this is most likely my last issue :) )
thank you for all the help
