### ISSUE TITLE
Disqus does not seem to be working on Github pages

### ISSUE THREAD

**Issue by fberrez** [nodejh/hugo-theme-cactus-plus#70]
hugo version: `Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown`

config.toml:
```toml
baseURL = "/"
languageCode = "en"
title = "fberrez.com"
theme = "cactus-plus"
googleAnalytics = ""

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
        [...]
	enableDisqus = true
	disqusShortname = "fberrez"
[...]
```

What?

Disqus cannot be loaded on a github pages website. It returns the error `We were unable to load Disqus. If you are a moderator please see our [troubleshooting guide](https://help.disqus.com/troubleshooting/im-receiving-the-message-we-were-unable-to-load-disqus).`.

It does not help to read the troubleshooting guide. See my Disqus config below:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/25006376/51979986-f243db00-248e-11e9-8473-f30952ad8b46.png">

<img width="823" alt="image" src="https://user-images.githubusercontent.com/25006376/51979997-fd970680-248e-11e9-9645-4a25298c7a18.png">
